DictionaryApiApp/DictionaryApiApp/Models/DefinitionModel.cs
using System.Text.Json.Serialization;

namespace DictionaryApiApp.Models
{
    public class DefinitionModel
    {
        [JsonPropertyName("definition")]
        public string Definition { get; set; }
        [JsonPropertyName("example")]
        public string Example { get; set; }
        [JsonPropertyName("synonyms")]
        public List<object> Synonyms { get; set; }
        [JsonPropertyName("antonyms")]
        public List<object> Antonyms { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Models/ErrorViewModel.cs
using System.Text.Json.Serialization;

namespace DictionaryApiApp.Models
{
    public class ErrorViewModel
    {
        [JsonPropertyName("title")]
        public string Title { get; set; }
        [JsonPropertyName("message")]
        public string Message { get; set; }
        [JsonPropertyName("resolution")]
        public string Resolution { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Models/InputWord.cs
namespace DictionaryApiApp.Models
{
    public class InputWord
    {
        public string Word { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Models/Meaning.cs
using System.Text.Json.Serialization;

namespace DictionaryApiApp.Models
{
    public class Meaning
    {
        [JsonPropertyName("partOfSpeech")]
        public string PartOfSpeech { get; set; }
        [JsonPropertyName("definitions")]
        public List<DefinitionModel> Definitions { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Models/Phonetic.cs
using System.Text.Json.Serialization;

namespace DictionaryApiApp.Models
{
    public class Phonetic
    {
        [JsonPropertyName("text")]
        public string Text { get; set; }
        [JsonPropertyName("audio")]
        public string Audio { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Models/WordInfo.cs
namespace DictionaryApiApp.Models
{
    public class WordInfo
    {
        public List<WordInfoElement> WordInfoElements { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Models/WordInfoElement.cs
using System.Text.Json.Serialization;

namespace DictionaryApiApp.Models
{
    public class WordInfoElement
    {
        [JsonPropertyName("word")]
        public string Word { get; set; }
        [JsonPropertyName("phonetic")]
        public string Phonetic { get; set; }
        [JsonPropertyName("phonetics")]
        public List<Phonetic> Phonetics { get; set; }
        [JsonPropertyName("origin")]
        public string Origin { get; set; }
        [JsonPropertyName("meanings")]
        public List<Meaning> Meanings { get; set; }
    }
}

DictionaryApiApp/DictionaryApiApp/Controllers/DictionaryController.cs
using DictionaryApiApp.Models;
using DictionaryApiApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace DictionaryApiApp.Controllers
{
    public class DictionaryController : Controller
    {
        private readonly ILogger<DictionaryController> _logger;
        private IWordInformationService _wordInformationService;

        public DictionaryController(ILogger<DictionaryController> logger, IWordInformationService wordInformationService)
        {
            _logger = logger;
            _wordInformationService = wordInformationService;
        }

        public async Task<IActionResult> GetWordInfo(InputWord model)
        {
            var response = "";
            try
            {
                if (string.IsNullOrEmpty(model?.Word))
                    return View();

                response = await _wordInformationService.GetWordInfoAsync(model?.Word);

                var wordInfo = new WordInfo()
                {
                    WordInfoElements = JsonSerializer.Deserialize<List<WordInfoElement>>(response)
                };
                return View(wordInfo);
            }
            catch (JsonException ex)
            {
                var errorInfo = JsonSerializer.Deserialize<ErrorViewModel>(response);
                _logger.LogDebug("Error: {0}  Message: {1}", errorInfo.Title, errorInfo.Message);
                return View("Error", errorInfo);
            }
            catch (Exception ex)
            {
                _logger.LogDebug("Error: {0}  Message: {1}", ex, ex.Message);
                var errorInfo = new ErrorViewModel() { Title = "Unknown error", Message = ex.Message};
                return View("Error", errorInfo);
            }
        }

        public IActionResult About()
        {
            return View();
        }

        /*[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }*/
    }
}

DictionaryApiApp/DictionaryApiApp/Views/Dictionary/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>This is an API dictionary application based on ASP.NET MVC.</p>

DictionaryApiApp/DictionaryApiApp/Views/Dictionary/GetWordInfo.cshtml
@model DictionaryApiApp.Models.WordInfo
<div class="text-center">
    <h1 class="display-4">Vocabulary</h1>
    <p>words info</a>.</p>
    @await Html.PartialAsync("InputWord", new InputWord() { Word = "" })

    <section>
        <div id="carouselExampleCaptions" class="carousel slide">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
            </div>
            @if (Model != null)
            {
                <div class="carousel-inner">

                    <div class="carousel-item active">
                        <table class="table">
                            @foreach (var wordInfoElement in Model.WordInfoElements.Take(1))
                            {
                                @foreach (var meaning in wordInfoElement.Meanings)
                                {
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(wordInfoElements => wordInfoElement.Meanings)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                @foreach (var defItem in meaning.Definitions)
                                                {
                                                    @Html.DisplayFor(modelItem => defItem.Definition)
                                                }
                                            </td>
                                        </tr>
                                    </tbody>
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(element => wordInfoElement.Phonetic)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(element => wordInfoElement.Phonetic)
                                            </td>
                                        </tr>
                                    </tbody>
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(element => wordInfoElement.Meanings.FirstOrDefault().Definitions.FirstOrDefault().Example)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in wordInfoElement.Meanings)
                                        {
                                            <tr>
                                                <td>
                                                    @foreach (var defItem in item.Definitions)
                                                    {
                                                        @Html.DisplayFor(modelItem => defItem.Example)
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                }
                            }
                        </table>
                    </div>

                    <div class="carousel-item">
                        <table class="table">
                            @foreach (var wordInfoElement in Model.WordInfoElements.Skip(1))
                            {
                                @foreach (var meaning in wordInfoElement.Meanings)
                                {
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(wordInfoElements => wordInfoElement.Meanings)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                @foreach (var defItem in meaning.Definitions)
                                                {
                                                    @Html.DisplayFor(modelItem => defItem.Definition)
                                                }
                                            </td>
                                        </tr>
                                    </tbody>
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(element => wordInfoElement.Phonetic)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(element => wordInfoElement.Phonetic)
                                            </td>
                                        </tr>
                                    </tbody>
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(element => wordInfoElement.Meanings.FirstOrDefault().Definitions.FirstOrDefault().Example)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in wordInfoElement.Meanings)
                                        {
                                            <tr>
                                                <td>
                                                    @foreach (var defItem in item.Definitions)
                                                    {
                                                        @Html.DisplayFor(modelItem => defItem.Example)
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                }
                            }
                        </table>
                    </div>
                </div>
            }
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </section>
</div>

DictionaryApiApp/DictionaryApiApp/Views/Dictionary/InputWord.cshtml
@model DictionaryApiApp.Models.InputWord

<form method="get">
    <input id="wordInput" asp-for="Word" />
    <input type="Submit" value="Search" />
</form>

DictionaryApiApp/DictionaryApiApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dictionary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DictionaryApiAppstyles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dictionary" asp-action="GetWordInfo">Dictionary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dictionary" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>